export const FETCH_BOOKINGS = "FETCH_BOOKINGS";
export const POST_BOOKING = "POST_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const FAILURE_BOOKING = "FAILURE_BOOKING";
